### ISSUE TITLE
Question about Step: 4 Run the extractor

### ISSUE THREAD

**Issue by Old-Lorry** [hynky1999/CmonCrawl#104]

**Comment by hynky1999** [comment]
Hey 👋,
I think the problem is that the provided config is not in correct format (not a valid JSON).

Could you try removing the comments ?
eg:
```
{
    "extractors_path": "./extractors",
    "routes": [
        {
            "regexes": [".*"],
            "extractors": [{
                "name": "my_extractor",
                "since": "2009-01-01",
                "to": "2025-01-01"
            }]
        }
    ]
}
```

I agree that the error is not very insightful, I will update the error and change readme so that it's clear one shouldn't use the comments in json.

**Comment by Old-Lorry** [comment]
Hello,


Thank you for your reply. It is a nice work.


Unfortunately, I could not remove the comment because there isn't any button to remove. Maybe you could remove it directly?&nbsp;



luoyl
***@***.***







                       
Original Email
                       
                     

Sender:"Hynek Kydlíček"< ***@***.*** &gt;;

Sent Time:2024/3/13 19:16

To:"hynky1999/CmonCrawl"< ***@***.*** &gt;;

Cc recipient:"Old-Lorry"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [hynky1999/CmonCrawl] Question about Step: 4 Run the extractor(Issue #104)




 
Hey 👋,
 I think the problem is that the provided config is not in correct format (not a valid JSON).
 
Could you try removing the comments ?
 eg:
 {     "extractors_path": "./extractors",     "routes": [         {             "regexes": [".*"],             "extractors": [{                 "name": "my_extractor",                 "since": "2009-01-01",                 "to": "2025-01-01"             }]         }     ] }  
I agree that the error is not very insightful, I will update the error and change readme so that it's clear one shouldn't use the comments in json.

**Comment by hynky1999** [comment]
Add better errors and update readme
